<?php
require __DIR__.'/config/db.php';$mensaje='';
try{if($_SERVER['REQUEST_METHOD']==='POST'){csrf();$clave=$_POST['password']??'';$email=trim($_POST['email']??'');
if(isset($_POST['registro'])){$nombre=trim($_POST['nombre']??'');if($nombre===''||mb_strlen($nombre)>100||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($email)>190||strlen($clave)<8||strlen($clave)>72)throw new RuntimeException('Nombre válido, email válido y contraseña de 8 a 72 bytes.');
$q=bd()->prepare('SELECT id FROM alumnos WHERE email=?');$q->execute([$email]);if($q->fetch())throw new RuntimeException('Ese email ya está registrado.');$q=bd()->prepare('INSERT INTO alumnos(nombre,email,password) VALUES(?,?,?)');$q->execute([$nombre,$email,password_hash($clave,PASSWORD_DEFAULT)]);$mensaje='Registro completado. Ya puedes iniciar sesión.';
}else{
if(strlen($clave)>72)throw new RuntimeException('Credenciales incorrectas.');
// Los alias de acceso solo se permiten para los dos usuarios de prueba.
if(in_array($email,['admin','alumno']))$email.='@lab.local';$q=bd()->prepare('SELECT id,nombre,email,password,rol FROM alumnos WHERE email=?');$q->execute([$email]);$usuario=$q->fetch();if(!$usuario||!password_verify($clave,$usuario['password']))throw new RuntimeException('Credenciales incorrectas.');session_regenerate_id(true);unset($usuario['password']);$_SESSION['alumno']=$usuario;$_SESSION['csrf']=bin2hex(random_bytes(32));header('Location: '.BASE_URL.'/index.php');exit;}}}
catch(Throwable $error){error_log($error->getMessage());$mensaje=$error instanceof PDOException?'No se pudo registrar al alumno. Comprueba si el email ya existe.':$error->getMessage();}
$titulo='Acceso al laboratorio';include __DIR__.'/includes/header.php'; ?>
<h1>Tu espacio de aprendizaje</h1><?php if($mensaje): ?><p class="aviso" role="status"><?=e($mensaje)?></p><?php endif; ?><div class="grid"><section><h2>Iniciar sesión</h2><form method="post"><input type="hidden" name="csrf" value="<?=e(token())?>"><label>Email o usuario de prueba <input name="email" required maxlength="190" autocomplete="username"></label><label>Contraseña <input type="password" name="password" required maxlength="72" autocomplete="current-password"></label><button>Entrar</button></form></section><section><h2>Registrarse</h2><form method="post"><input type="hidden" name="csrf" value="<?=e(token())?>"><input type="hidden" name="registro" value="1"><label>Nombre <input name="nombre" required maxlength="100" autocomplete="name"></label><label>Email <input name="email" type="email" required maxlength="190" autocomplete="email"></label><label>Contraseña <input name="password" type="password" required minlength="8" maxlength="72" autocomplete="new-password"></label><button>Crear cuenta</button></form></section></div><?php include __DIR__.'/includes/footer.php'; ?>
