<?php
$contenidos = [
1=>['Evolución del desarrollo web','01-evolucion','La web pasó de documentos enlazados a aplicaciones que combinan servicios, interfaces y datos. Cada etapa añade posibilidades; HTML estático sigue siendo útil.',[
['Web 1.0','Documentos HTML estáticos enlazados.'],['CGI','Programas ejecutados por el servidor para generar respuestas.'],['PHP / ASP','Generación dinámica con lógica y bases de datos.'],['AJAX','Peticiones asíncronas sin recargar todo el documento.'],['Web 2.0','Participación, colaboración y contenido de usuarios.'],['SPA','La interfaz cambia en el navegador usando APIs.'],['Nube','Infraestructura y servicios bajo demanda.'],['PWA','Aplicaciones con capacidades instalables y trabajo sin conexión.'],['Jamstack','Contenido preconstruido, JavaScript y APIs.'],['IA en la web','Funciones que generan o clasifican contenido; requieren validación.']]],
2=>['Arquitectura cliente-servidor','02-cliente-servidor','El navegador presenta la interfaz. DNS resuelve nombres; Apache recibe HTTP; PHP ejecuta la lógica; MySQL conserva datos. La respuesta vuelve al navegador. En localhost, el nombre suele resolverse localmente sin una consulta DNS externa.',[]],
3=>['HTTP / HTTPS','03-http-https','HTTP intercambia peticiones y respuestas. GET consulta; POST crea o procesa; PUT reemplaza; DELETE elimina. 200 indica éxito, 400 datos inválidos, 404 recurso ausente y 500 error del servidor. Las cabeceras describen contenido y contexto. Las cookies viajan con las peticiones; la sesión conserva datos en el servidor. HTTPS usa TLS para cifrar y autenticar la conexión; SSL es su antecesor.',[]],
4=>['Tipos de aplicaciones web','04-tipos-apps','Una MPA solicita documentos completos en cada navegación. Una SPA actualiza la interfaz con JavaScript y una API. Ambas pueden usar la misma base de datos. PWA describe capacidades adicionales y no implica una arquitectura única.',[
['Estática','HTML preconstruido: portafolio o documentación.'],['Dinámica','El servidor genera contenido según datos o usuario.'],['SPA','Actualizaciones de interfaz mediante API.'],['MPA','Navegaciones y formularios cargan documentos.'],['PWA','Manifiesto y capacidades progresivas, como caché sin conexión.'],['E-commerce','Catálogo, pedidos y pagos.'],['CMS','Gestión editorial de contenidos.'],['API REST','Recursos accesibles mediante HTTP, habitualmente JSON.']]],
5=>['Plataformas y despliegue','05-plataformas','El entorno se elige según lenguaje, almacenamiento, control operativo y presupuesto. Una aplicación PHP con MySQL necesita un servidor compatible y una base de datos; un alojamiento de archivos estáticos por sí solo no ejecuta PHP.',[
['XAMPP / Laragon','Desarrollo local con servicios integrados.'],['Docker','Contenedores reproducibles; requiere configurar imágenes y volúmenes.'],['Hosting compartido','Administración sencilla; recursos y configuración limitados.'],['VPS','Control del servidor; exige mantenimiento y seguridad.'],['Render / Railway','PaaS: despliegue administrado, compatibilidad según servicio e imagen.'],['Netlify / Vercel / GitHub Pages','Publicación estática o funciones según proveedor; este PHP no se sube tal cual.']]],
6=>['Configuración del entorno','06-entorno','XAMPP integra Apache, PHP y MariaDB. El panel inicia los servicios; phpMyAdmin administra bases de datos. Verificar el entorno permite distinguir errores de código de errores de configuración.',[]]
];
$preguntas_semilla = [
1=>[['¿Qué caracteriza a Web 1.0?',['Documentos estáticos','Sesiones de PHP','IA generativa'],0],['¿Qué permite AJAX?',['Peticiones sin recargar todo','Eliminar HTTP','Ejecutar PHP en el navegador'],0],['¿Dónde se ejecuta PHP?',['Navegador','Servidor','DNS'],1],['¿Qué caracteriza a una SPA?',['Actualiza la interfaz con JavaScript','Solo admite HTML estático','No usa HTTP'],0],['¿Qué aporta una PWA?',['Capacidades progresivas como instalación','Reemplaza MySQL','Necesita CGI'],0]],
2=>[['¿Qué resuelve DNS?',['Nombres a direcciones','Consultas SQL','Contraseñas'],0],['¿Qué hace Apache?',['Recibe peticiones HTTP','Dibuja botones','Ejecuta JavaScript del cliente'],0],['¿Dónde corre JavaScript de la interfaz?',['MySQL','Navegador','DNS'],1],['¿Qué conserva MySQL?',['Datos persistentes','Solo estilos','Certificados TLS'],0],['¿Qué devuelve una API JSON?',['Datos estructurados','Código PHP para ejecutar en el cliente','Un servidor nuevo'],0]],
3=>[['¿Qué método consulta recursos?',['GET','DELETE','PUT'],0],['¿Qué significa 404?',['Éxito','Recurso no encontrado','Redirección'],1],['¿Qué añade HTTPS?',['Cifrado TLS','Una base de datos','Elimina cookies'],0],['¿Dónde se guardan los datos de sesión de PHP?',['Servidor','Solo en CSS','DNS'],0],['¿Qué método se usa para eliminar un recurso?',['GET','DELETE','PUT'],1]],
4=>[['¿Qué hace una MPA al enviar un formulario tradicional?',['Recarga un documento','No contacta el servidor','Ejecuta SQL en el cliente'],0],['¿Qué usa este CRUD SPA?',['fetch y JSON','Composer','FTP'],0],['¿Qué significa CRUD?',['Crear, leer, actualizar y eliminar','Cifrar rutas','Solo consultar'],0],['¿Qué es un CMS?',['Gestor de contenidos','Certificado','Método HTTP'],0],['¿Pueden SPA y MPA compartir tabla?',['Sí','Nunca','Solo sin PHP'],0]],
5=>[['¿Qué ofrece un VPS?',['Control del servidor','Solo archivos HTML','Un navegador'],0],['¿Qué necesita esta aplicación?',['PHP y MySQL','Solo alojamiento estático','Solo DNS'],0],['¿Para qué sirve un dominio?',['Identificar un sitio con un nombre','Guardar tareas','Cifrar contraseñas'],0],['¿Qué debe habilitarse al publicar?',['HTTPS','display_errors público','Contraseñas vacías'],0],['¿Qué permite Docker?',['Entornos en contenedores','Eliminar validaciones','Reemplazar HTTP'],0]],
6=>[['¿Qué extensión permite PDO con MySQL?',['pdo_mysql','gd','zip'],0],['¿Cuál es el puerto HTTP habitual?',['80','3306','22'],0],['¿Qué servicio usa normalmente 3306?',['MySQL','Apache HTTP','DNS'],0],['¿Qué herramienta administra la BD en XAMPP?',['phpMyAdmin','CSS','Git log'],0],['¿Qué registra Git?',['Historial de cambios','Sesiones PHP','Certificados automáticamente'],0]]
];
$items_despliegue=['Subir archivos por FTP/SFTP','Crear e importar la base de datos','Configurar credenciales y variables de entorno','Configurar dominio y DNS','Habilitar HTTPS','Desactivar errores públicos y probar copias de seguridad'];
