CREATE DATABASE IF NOT EXISTS lab_web CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE lab_web;
CREATE TABLE IF NOT EXISTS alumnos (id INT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(100) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,rol ENUM('alumno','admin') NOT NULL DEFAULT 'alumno',fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS modulos (id INT PRIMARY KEY,titulo VARCHAR(150) NOT NULL,slug VARCHAR(100) NOT NULL,orden INT NOT NULL);
CREATE TABLE IF NOT EXISTS preguntas (id INT PRIMARY KEY,modulo_id INT NOT NULL,enunciado TEXT NOT NULL,opciones JSON NOT NULL,respuesta_correcta INT NOT NULL,FOREIGN KEY(modulo_id) REFERENCES modulos(id));
CREATE TABLE IF NOT EXISTS resultados (id INT AUTO_INCREMENT PRIMARY KEY,alumno_id INT NOT NULL,modulo_id INT NOT NULL,puntaje DECIMAL(4,2) NOT NULL,fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(alumno_id) REFERENCES alumnos(id),FOREIGN KEY(modulo_id) REFERENCES modulos(id));
CREATE TABLE IF NOT EXISTS tareas (id INT AUTO_INCREMENT PRIMARY KEY,alumno_id INT NOT NULL,titulo VARCHAR(150) NOT NULL,completada BOOLEAN NOT NULL DEFAULT 0,creada_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(alumno_id) REFERENCES alumnos(id));
CREATE TABLE IF NOT EXISTS checklist_despliegue (id INT AUTO_INCREMENT PRIMARY KEY,alumno_id INT NOT NULL,item VARCHAR(150) NOT NULL,completado BOOLEAN NOT NULL DEFAULT 0,UNIQUE KEY alumno_item(alumno_id,item),FOREIGN KEY(alumno_id) REFERENCES alumnos(id));
INSERT IGNORE INTO modulos VALUES (1,'Evolución del desarrollo web','01-evolucion',1);
INSERT IGNORE INTO modulos VALUES (2,'Arquitectura cliente-servidor','02-cliente-servidor',2);
INSERT IGNORE INTO modulos VALUES (3,'HTTP / HTTPS','03-http-https',3);
INSERT IGNORE INTO modulos VALUES (4,'Tipos de aplicaciones web','04-tipos-apps',4);
INSERT IGNORE INTO modulos VALUES (5,'Plataformas y despliegue','05-plataformas',5);
INSERT IGNORE INTO modulos VALUES (6,'Configuración del entorno','06-entorno',6);
INSERT IGNORE INTO preguntas VALUES (1,1,'¿Qué caracteriza a Web 1.0?','["Documentos estáticos","Sesiones de PHP","IA generativa"]',0);
INSERT IGNORE INTO preguntas VALUES (2,1,'¿Qué permite AJAX?','["Peticiones sin recargar todo","Eliminar HTTP","Ejecutar PHP en el navegador"]',0);
INSERT IGNORE INTO preguntas VALUES (3,1,'¿Dónde se ejecuta PHP?','["Navegador","Servidor","DNS"]',1);
INSERT IGNORE INTO preguntas VALUES (4,1,'¿Qué caracteriza a una SPA?','["Actualiza la interfaz con JavaScript","Solo admite HTML estático","No usa HTTP"]',0);
INSERT IGNORE INTO preguntas VALUES (5,1,'¿Qué aporta una PWA?','["Capacidades progresivas como instalación","Reemplaza MySQL","Necesita CGI"]',0);
INSERT IGNORE INTO preguntas VALUES (6,2,'¿Qué resuelve DNS?','["Nombres a direcciones","Consultas SQL","Contraseñas"]',0);
INSERT IGNORE INTO preguntas VALUES (7,2,'¿Qué hace Apache?','["Recibe peticiones HTTP","Dibuja botones","Ejecuta JavaScript del cliente"]',0);
INSERT IGNORE INTO preguntas VALUES (8,2,'¿Dónde corre JavaScript de la interfaz?','["MySQL","Navegador","DNS"]',1);
INSERT IGNORE INTO preguntas VALUES (9,2,'¿Qué conserva MySQL?','["Datos persistentes","Solo estilos","Certificados TLS"]',0);
INSERT IGNORE INTO preguntas VALUES (10,2,'¿Qué devuelve una API JSON?','["Datos estructurados","Código PHP para ejecutar en el cliente","Un servidor nuevo"]',0);
INSERT IGNORE INTO preguntas VALUES (11,3,'¿Qué método consulta recursos?','["GET","DELETE","PUT"]',0);
INSERT IGNORE INTO preguntas VALUES (12,3,'¿Qué significa 404?','["Éxito","Recurso no encontrado","Redirección"]',1);
INSERT IGNORE INTO preguntas VALUES (13,3,'¿Qué añade HTTPS?','["Cifrado TLS","Una base de datos","Elimina cookies"]',0);
INSERT IGNORE INTO preguntas VALUES (14,3,'¿Dónde se guardan los datos de sesión de PHP?','["Servidor","Solo en CSS","DNS"]',0);
INSERT IGNORE INTO preguntas VALUES (15,3,'¿Qué método se usa para eliminar un recurso?','["GET","DELETE","PUT"]',1);
INSERT IGNORE INTO preguntas VALUES (16,4,'¿Qué hace una MPA al enviar un formulario tradicional?','["Recarga un documento","No contacta el servidor","Ejecuta SQL en el cliente"]',0);
INSERT IGNORE INTO preguntas VALUES (17,4,'¿Qué usa este CRUD SPA?','["fetch y JSON","Composer","FTP"]',0);
INSERT IGNORE INTO preguntas VALUES (18,4,'¿Qué significa CRUD?','["Crear, leer, actualizar y eliminar","Cifrar rutas","Solo consultar"]',0);
INSERT IGNORE INTO preguntas VALUES (19,4,'¿Qué es un CMS?','["Gestor de contenidos","Certificado","Método HTTP"]',0);
INSERT IGNORE INTO preguntas VALUES (20,4,'¿Pueden SPA y MPA compartir tabla?','["Sí","Nunca","Solo sin PHP"]',0);
INSERT IGNORE INTO preguntas VALUES (21,5,'¿Qué ofrece un VPS?','["Control del servidor","Solo archivos HTML","Un navegador"]',0);
INSERT IGNORE INTO preguntas VALUES (22,5,'¿Qué necesita esta aplicación?','["PHP y MySQL","Solo alojamiento estático","Solo DNS"]',0);
INSERT IGNORE INTO preguntas VALUES (23,5,'¿Para qué sirve un dominio?','["Identificar un sitio con un nombre","Guardar tareas","Cifrar contraseñas"]',0);
INSERT IGNORE INTO preguntas VALUES (24,5,'¿Qué debe habilitarse al publicar?','["HTTPS","display_errors público","Contraseñas vacías"]',0);
INSERT IGNORE INTO preguntas VALUES (25,5,'¿Qué permite Docker?','["Entornos en contenedores","Eliminar validaciones","Reemplazar HTTP"]',0);
INSERT IGNORE INTO preguntas VALUES (26,6,'¿Qué extensión permite PDO con MySQL?','["pdo_mysql","gd","zip"]',0);
INSERT IGNORE INTO preguntas VALUES (27,6,'¿Cuál es el puerto HTTP habitual?','["80","3306","22"]',0);
INSERT IGNORE INTO preguntas VALUES (28,6,'¿Qué servicio usa normalmente 3306?','["MySQL","Apache HTTP","DNS"]',0);
INSERT IGNORE INTO preguntas VALUES (29,6,'¿Qué herramienta administra la BD en XAMPP?','["phpMyAdmin","CSS","Git log"]',0);
INSERT IGNORE INTO preguntas VALUES (30,6,'¿Qué registra Git?','["Historial de cambios","Sesiones PHP","Certificados automáticamente"]',0);
INSERT IGNORE INTO alumnos(nombre,email,password,rol) VALUES ('admin','admin@lab.local','$2y$10$JdTzDSTMH6yiVehd4VpwgOCqPQg5zEve3xvn0bM1GsmD3TwUSP0W6','admin');
INSERT IGNORE INTO alumnos(nombre,email,password,rol) VALUES ('alumno','alumno@lab.local','$2y$10$tUkdd0KhNkL51SpwR8HXqemLlYj9zVbaXZwOWWSAV2qoipaepdoiq','alumno');
INSERT INTO tareas(alumno_id,titulo) SELECT id,'Comparar el CRUD MPA y SPA' FROM alumnos WHERE email='alumno@lab.local' AND NOT EXISTS (SELECT 1 FROM tareas);
